-- Getit – Questions Box: core schema
-- Sessions -> participants -> questions, plus AI-generated question groups.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

create table public.sessions (
  id          uuid primary key default gen_random_uuid(),
  code        text not null unique check (code ~ '^[A-Z0-9]{6}$'),
  status      text not null default 'active' check (status in ('active', 'ended')),
  created_at  timestamptz not null default now(),
  ended_at    timestamptz,
  -- Serialises AI classification per session so two concurrent workers never
  -- create duplicate groups for the same concept.
  classifier_locked_until timestamptz
);

-- Secret used by the instructor's browser to manage its session (e.g. end it).
-- Kept in its own table with RLS and no policies so anon can never read it.
create table public.session_host_keys (
  session_id uuid primary key references public.sessions(id) on delete cascade,
  host_key   uuid not null default gen_random_uuid()
);

create table public.participants (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references public.sessions(id) on delete cascade,
  display_name  text not null check (char_length(btrim(display_name)) between 1 and 60),
  created_at    timestamptz not null default now()
);
create index participants_session_idx on public.participants(session_id);

create table public.question_groups (
  id                       uuid primary key default gen_random_uuid(),
  session_id               uuid not null references public.sessions(id) on delete cascade,
  title                    text not null,
  representative_question  text not null,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);
create index question_groups_session_idx on public.question_groups(session_id);

create table public.questions (
  id                      uuid primary key default gen_random_uuid(),
  session_id              uuid not null references public.sessions(id) on delete cascade,
  participant_id          uuid not null references public.participants(id) on delete cascade,
  text                    text not null check (char_length(btrim(text)) between 1 and 1000),
  created_at              timestamptz not null default now(),
  -- A question belongs to at most one group.
  group_id                uuid references public.question_groups(id) on delete set null,
  classification_status   text not null default 'pending'
                            check (classification_status in ('pending', 'processing', 'classified')),
  classification_attempts integer not null default 0,
  classification_error    text,
  classification_updated_at timestamptz not null default now(),
  -- Idempotency key generated by the submitting browser; a retried submit
  -- after a network blip can never create a second copy of the question.
  client_request_id       uuid unique
);
create index questions_session_idx on public.questions(session_id, created_at desc);
create index questions_pending_idx on public.questions(session_id, created_at)
  where classification_status <> 'classified';
create index questions_group_idx on public.questions(group_id);

-- ---------------------------------------------------------------------------
-- Row level security
-- MVP has no accounts: anyone with the anon key may read session data (needed
-- for Realtime) and may join / ask in *active* sessions. All AI writes happen
-- in the Edge Function with the service role, which bypasses RLS.
-- ---------------------------------------------------------------------------

alter table public.sessions          enable row level security;
alter table public.session_host_keys enable row level security;
alter table public.participants      enable row level security;
alter table public.question_groups   enable row level security;
alter table public.questions         enable row level security;

create policy "read sessions"  on public.sessions        for select using (true);
create policy "read participants" on public.participants for select using (true);
create policy "read groups"    on public.question_groups for select using (true);
create policy "read questions" on public.questions       for select using (true);

create policy "join active session" on public.participants for insert
  with check (exists (select 1 from public.sessions s
                      where s.id = session_id and s.status = 'active'));

create policy "ask in active session" on public.questions for insert
  with check (
    classification_status = 'pending'
    and group_id is null
    and classification_attempts = 0
    and exists (select 1 from public.sessions s
                where s.id = session_id and s.status = 'active')
    and exists (select 1 from public.participants p
                where p.id = participant_id and p.session_id = questions.session_id)
  );

-- Only expose the columns the browser needs to write.
revoke insert, update, delete on public.sessions from anon, authenticated;
revoke all on public.session_host_keys from anon, authenticated;
revoke update, delete on public.participants, public.questions, public.question_groups from anon, authenticated;
revoke insert on public.question_groups from anon, authenticated;

-- ---------------------------------------------------------------------------
-- RPCs
-- ---------------------------------------------------------------------------

-- Create a session with a unique 6-character code (ambiguous 0/O/1/I omitted).
create or replace function public.create_session()
returns table (id uuid, code text, host_key uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  alphabet constant text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  new_code text;
  new_id uuid;
  new_key uuid;
begin
  loop
    new_code := '';
    for i in 1..6 loop
      new_code := new_code || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
    end loop;
    begin
      insert into sessions (code) values (new_code) returning sessions.id into new_id;
      exit;
    exception when unique_violation then
      -- collision: try another code
    end;
  end loop;
  insert into session_host_keys (session_id) values (new_id) returning session_host_keys.host_key into new_key;
  return query select new_id, new_code, new_key;
end;
$$;

create or replace function public.end_session(p_session_id uuid, p_host_key uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (select 1 from session_host_keys k
                 where k.session_id = p_session_id and k.host_key = p_host_key) then
    raise exception 'Not allowed to end this session' using errcode = '42501';
  end if;
  update sessions set status = 'ended', ended_at = now() where id = p_session_id;
  return true;
end;
$$;

-- Classifier lock (called by the Edge Function with the service role).
create or replace function public.try_acquire_classifier_lock(p_session_id uuid, p_seconds integer default 90)
returns boolean
language sql
security definer
set search_path = public
as $$
  with claimed as (
    update sessions
       set classifier_locked_until = now() + make_interval(secs => p_seconds)
     where id = p_session_id
       and (classifier_locked_until is null or classifier_locked_until < now())
    returning 1
  )
  select exists (select 1 from claimed);
$$;

create or replace function public.extend_classifier_lock(p_session_id uuid, p_seconds integer default 90)
returns void
language sql
security definer
set search_path = public
as $$
  update sessions set classifier_locked_until = now() + make_interval(secs => p_seconds)
   where id = p_session_id;
$$;

create or replace function public.release_classifier_lock(p_session_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update sessions set classifier_locked_until = null where id = p_session_id;
$$;

revoke execute on function public.try_acquire_classifier_lock(uuid, integer) from public, anon, authenticated;
revoke execute on function public.extend_classifier_lock(uuid, integer)      from public, anon, authenticated;
revoke execute on function public.release_classifier_lock(uuid)              from public, anon, authenticated;
grant execute on function public.try_acquire_classifier_lock(uuid, integer) to service_role;
grant execute on function public.extend_classifier_lock(uuid, integer)      to service_role;
grant execute on function public.release_classifier_lock(uuid)              to service_role;
grant execute on function public.create_session() to anon, authenticated;
grant execute on function public.end_session(uuid, uuid) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Realtime
-- ---------------------------------------------------------------------------

alter publication supabase_realtime add table public.sessions;
alter publication supabase_realtime add table public.participants;
alter publication supabase_realtime add table public.questions;
alter publication supabase_realtime add table public.question_groups;
